=begin
#Betfair: Exchange Streaming API

#API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)

OpenAPI spec version: 1.0.1423

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module SwaggerClient

  class Order
    # Side - the side of the order
    attr_accessor :side

    # Size Voided - the amount of the order that has been voided
    attr_accessor :sv

    # Persistence Type - whether the order will persist at in play or not (L = LAPSE, P = PERSIST, MOC = Market On Close)
    attr_accessor :pt

    # Order Type - the type of the order (L = LIMIT, MOC = MARKET_ON_CLOSE, LOC = LIMIT_ON_CLOSE)
    attr_accessor :ot

    # Price - the original placed price of the order
    attr_accessor :p

    # Size Cancelled - the amount of the order that has been cancelled
    attr_accessor :sc

    # Regulator Code - the regulator of the order
    attr_accessor :rc

    # Size - the original placed size of the order
    attr_accessor :s

    # Placed Date - the date the order was placed
    attr_accessor :pd

    # Regulator Auth Code - the auth code returned by the regulator
    attr_accessor :rac

    # Matched Date - the date the order was matched (null if the order is not matched)
    attr_accessor :md

    # Size Lapsed - the amount of the order that has been lapsed
    attr_accessor :sl

    # Average Price Matched - the average price the order was matched at (null if the order is not matched
    attr_accessor :avp

    # Size Matched - the amount of the order that has been matched
    attr_accessor :sm

    # Order Reference - the customer's order reference for this order (empty string if one was not set)
    attr_accessor :rfo

    # Bet Id - the id of the order
    attr_accessor :id

    # BSP Liability - the BSP liability of the order (null if the order is not a BSP order)
    attr_accessor :bsp

    # Strategy Reference - the customer's strategy reference for this order (empty string if one was not set)
    attr_accessor :rfs

    # Status - the status of the order (E = EXECUTABLE, EC = EXECUTION_COMPLETE)
    attr_accessor :status

    # Size Remaining - the amount of the order that is remaining unmatched
    attr_accessor :sr

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'side' => :'side',
        :'sv' => :'sv',
        :'pt' => :'pt',
        :'ot' => :'ot',
        :'p' => :'p',
        :'sc' => :'sc',
        :'rc' => :'rc',
        :'s' => :'s',
        :'pd' => :'pd',
        :'rac' => :'rac',
        :'md' => :'md',
        :'sl' => :'sl',
        :'avp' => :'avp',
        :'sm' => :'sm',
        :'rfo' => :'rfo',
        :'id' => :'id',
        :'bsp' => :'bsp',
        :'rfs' => :'rfs',
        :'status' => :'status',
        :'sr' => :'sr'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'side' => :'String',
        :'sv' => :'Float',
        :'pt' => :'String',
        :'ot' => :'String',
        :'p' => :'Float',
        :'sc' => :'Float',
        :'rc' => :'String',
        :'s' => :'Float',
        :'pd' => :'Integer',
        :'rac' => :'String',
        :'md' => :'Integer',
        :'sl' => :'Float',
        :'avp' => :'Float',
        :'sm' => :'Float',
        :'rfo' => :'String',
        :'id' => :'String',
        :'bsp' => :'Float',
        :'rfs' => :'String',
        :'status' => :'String',
        :'sr' => :'Float'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'side')
        self.side = attributes[:'side']
      end

      if attributes.has_key?(:'sv')
        self.sv = attributes[:'sv']
      end

      if attributes.has_key?(:'pt')
        self.pt = attributes[:'pt']
      end

      if attributes.has_key?(:'ot')
        self.ot = attributes[:'ot']
      end

      if attributes.has_key?(:'p')
        self.p = attributes[:'p']
      end

      if attributes.has_key?(:'sc')
        self.sc = attributes[:'sc']
      end

      if attributes.has_key?(:'rc')
        self.rc = attributes[:'rc']
      end

      if attributes.has_key?(:'s')
        self.s = attributes[:'s']
      end

      if attributes.has_key?(:'pd')
        self.pd = attributes[:'pd']
      end

      if attributes.has_key?(:'rac')
        self.rac = attributes[:'rac']
      end

      if attributes.has_key?(:'md')
        self.md = attributes[:'md']
      end

      if attributes.has_key?(:'sl')
        self.sl = attributes[:'sl']
      end

      if attributes.has_key?(:'avp')
        self.avp = attributes[:'avp']
      end

      if attributes.has_key?(:'sm')
        self.sm = attributes[:'sm']
      end

      if attributes.has_key?(:'rfo')
        self.rfo = attributes[:'rfo']
      end

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'bsp')
        self.bsp = attributes[:'bsp']
      end

      if attributes.has_key?(:'rfs')
        self.rfs = attributes[:'rfs']
      end

      if attributes.has_key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.has_key?(:'sr')
        self.sr = attributes[:'sr']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      side_validator = EnumAttributeValidator.new('String', ["B", "L"])
      return false unless side_validator.valid?(@side)
      pt_validator = EnumAttributeValidator.new('String', ["L", "P", "MOC"])
      return false unless pt_validator.valid?(@pt)
      ot_validator = EnumAttributeValidator.new('String', ["L", "LOC", "MOC"])
      return false unless ot_validator.valid?(@ot)
      status_validator = EnumAttributeValidator.new('String', ["E", "EC"])
      return false unless status_validator.valid?(@status)
      return true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] side Object to be assigned
    def side=(side)
      validator = EnumAttributeValidator.new('String', ["B", "L"])
      unless validator.valid?(side)
        fail ArgumentError, "invalid value for 'side', must be one of #{validator.allowable_values}."
      end
      @side = side
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] pt Object to be assigned
    def pt=(pt)
      validator = EnumAttributeValidator.new('String', ["L", "P", "MOC"])
      unless validator.valid?(pt)
        fail ArgumentError, "invalid value for 'pt', must be one of #{validator.allowable_values}."
      end
      @pt = pt
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ot Object to be assigned
    def ot=(ot)
      validator = EnumAttributeValidator.new('String', ["L", "LOC", "MOC"])
      unless validator.valid?(ot)
        fail ArgumentError, "invalid value for 'ot', must be one of #{validator.allowable_values}."
      end
      @ot = ot
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["E", "EC"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for 'status', must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          side == o.side &&
          sv == o.sv &&
          pt == o.pt &&
          ot == o.ot &&
          p == o.p &&
          sc == o.sc &&
          rc == o.rc &&
          s == o.s &&
          pd == o.pd &&
          rac == o.rac &&
          md == o.md &&
          sl == o.sl &&
          avp == o.avp &&
          sm == o.sm &&
          rfo == o.rfo &&
          id == o.id &&
          bsp == o.bsp &&
          rfs == o.rfs &&
          status == o.status &&
          sr == o.sr
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [side, sv, pt, ot, p, sc, rc, s, pd, rac, md, sl, avp, sm, rfo, id, bsp, rfs, status, sr].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
