=begin
#Betfair: Exchange Streaming API

#API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)

OpenAPI spec version: 1.0.1423

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module SwaggerClient

  class OrderChangeMessage
    # The operation type
    attr_accessor :op

    # Client generated unique id to link request with response (like json rpc)
    attr_accessor :id

    # Change Type - set to indicate the type of change - if null this is a delta)
    attr_accessor :ct

    # Token value (non-null) should be stored and passed in a MarketSubscriptionMessage to resume subscription (in case of disconnect)
    attr_accessor :clk

    # Heartbeat Milliseconds - the heartbeat rate (may differ from requested: bounds are 500 to 30000)
    attr_accessor :heartbeat_ms

    # Publish Time (in millis since epoch) that the changes were generated
    attr_accessor :pt

    # OrderMarketChanges - the modifications to account's orders (will be null on a heartbeat
    attr_accessor :oc

    # Token value (non-null) should be stored and passed in a MarketSubscriptionMessage to resume subscription (in case of disconnect)
    attr_accessor :initial_clk

    # Conflate Milliseconds - the conflation rate (may differ from that requested if subscription is delayed)
    attr_accessor :conflate_ms

    # Segment Type - if the change is split into multiple segments, this denotes the beginning and end of a change, and segments in between. Will be null if data is not segmented
    attr_accessor :segment_type

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'op' => :'op',
        :'id' => :'id',
        :'ct' => :'ct',
        :'clk' => :'clk',
        :'heartbeat_ms' => :'heartbeatMs',
        :'pt' => :'pt',
        :'oc' => :'oc',
        :'initial_clk' => :'initialClk',
        :'conflate_ms' => :'conflateMs',
        :'segment_type' => :'segmentType'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'op' => :'String',
        :'id' => :'Integer',
        :'ct' => :'String',
        :'clk' => :'String',
        :'heartbeat_ms' => :'Integer',
        :'pt' => :'Integer',
        :'oc' => :'Array<OrderMarketChange>',
        :'initial_clk' => :'String',
        :'conflate_ms' => :'Integer',
        :'segment_type' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'op')
        self.op = attributes[:'op']
      end

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'ct')
        self.ct = attributes[:'ct']
      end

      if attributes.has_key?(:'clk')
        self.clk = attributes[:'clk']
      end

      if attributes.has_key?(:'heartbeatMs')
        self.heartbeat_ms = attributes[:'heartbeatMs']
      end

      if attributes.has_key?(:'pt')
        self.pt = attributes[:'pt']
      end

      if attributes.has_key?(:'oc')
        if (value = attributes[:'oc']).is_a?(Array)
          self.oc = value
        end
      end

      if attributes.has_key?(:'initialClk')
        self.initial_clk = attributes[:'initialClk']
      end

      if attributes.has_key?(:'conflateMs')
        self.conflate_ms = attributes[:'conflateMs']
      end

      if attributes.has_key?(:'segmentType')
        self.segment_type = attributes[:'segmentType']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      ct_validator = EnumAttributeValidator.new('String', ["SUB_IMAGE", "RESUB_DELTA", "HEARTBEAT"])
      return false unless ct_validator.valid?(@ct)
      segment_type_validator = EnumAttributeValidator.new('String', ["SEG_START", "SEG", "SEG_END"])
      return false unless segment_type_validator.valid?(@segment_type)
      return true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ct Object to be assigned
    def ct=(ct)
      validator = EnumAttributeValidator.new('String', ["SUB_IMAGE", "RESUB_DELTA", "HEARTBEAT"])
      unless validator.valid?(ct)
        fail ArgumentError, "invalid value for 'ct', must be one of #{validator.allowable_values}."
      end
      @ct = ct
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] segment_type Object to be assigned
    def segment_type=(segment_type)
      validator = EnumAttributeValidator.new('String', ["SEG_START", "SEG", "SEG_END"])
      unless validator.valid?(segment_type)
        fail ArgumentError, "invalid value for 'segment_type', must be one of #{validator.allowable_values}."
      end
      @segment_type = segment_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          op == o.op &&
          id == o.id &&
          ct == o.ct &&
          clk == o.clk &&
          heartbeat_ms == o.heartbeat_ms &&
          pt == o.pt &&
          oc == o.oc &&
          initial_clk == o.initial_clk &&
          conflate_ms == o.conflate_ms &&
          segment_type == o.segment_type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [op, id, ct, clk, heartbeat_ms, pt, oc, initial_clk, conflate_ms, segment_type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
